name: apcms
services:
  api:
    container_name: cms-api
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
      - 3000:3000
    environment:
      - APP_MODE=production
    volumes:
      - ../seed.json:/app/seed.json
    env_file:
      - path: ../api/.env
        required: false
    networks:
      - apcms-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      mail:
        condition: service_started
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: cms-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=apcms
      - POSTGRES_PASSWORD=apcms
      - POSTGRES_DB=apcms
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - apcms-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U apcms -d apcms"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: cms-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - apcms-network
    restart: unless-stopped

  mail:
    image: aprilpollo/mail:latest
    container_name: cms-mail
    environment:
      - APP_NAME=EMAIL_SERVICE
      - APP_VERSION=0.1.1
      - API_PORT=8081
      - APP_MODE=production
      - API_SHUTDOWN_TIMEOUT_SECONDS=30
      - ALLOWED_CREDENTIAL_ORIGINS=*
      - TIME_ZONE=Asia/Bangkok

    env_file:
      - path: ../api/.env
      
    ports:
      - "8981:8081"
    networks:
      - apcms-network
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
    container_name: cms-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=12345678
    command: >
      minio server /mnt/data
      --console-address ":9001"
     # --license /minio.license
    volumes:
      - ./data:/mnt/data
      #- ./minio.license:/minio.license
    networks:
      - apcms-network
    restart: unless-stopped


networks:
  apcms-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local